CREATE TABLE product_catalog (
    id BIGINT AUTO_INCREMENT,
    code CHAR(8) NOT NULL UNIQUE,
    type VARCHAR(50) NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(255) NOT NULL
);

CREATE TABLE shopping_cart (
    id BIGINT AUTO_INCREMENT,
    username CHAR(100) NOT NULL UNIQUE
);

CREATE TABLE cart_item_group (
    id BIGINT AUTO_INCREMENT,
    username CHAR(100) NOT NULL UNIQUE,
    product_code CHAR(8) NOT NULL,
    quantity INT NOT NULL DEFAULT 0
);


--Hibernate: create table cart_item_group (id bigint generated by default as identity, product_code varchar(255), quantity bigint, cart_id bigint, primary key (id))
--Hibernate: create table product_catalog (id bigint generated by default as identity, code varchar(255), description varchar(255), name varchar(255), type varchar(255), primary key (id))
--Hibernate: create table shopping_cart (id bigint generated by default as identity, username varchar(255), primary key (id))
--Hibernate: alter table shopping_cart add constraint UK_p5plppa64be9yoh8q0r5d1iud unique (username)
--Hibernate: alter table cart_item_group add constraint FKkfv4n8egoy9dkjt1areacyxwa foreign key (cart_id) references shopping_cart